spring.application.name=crud-springboot

spring.datasource.url=jdbc:postgresql://localhost:5432/GedApp
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Swagger + Springfox fix for Spring Boot 2.6+
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
